export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RECEIVE = 'LOGOUT_RECEIVE';
export const LOGOUT_ERROR = 'LOGOUT_RECEIVE';

export const SEND_ACTION_REQUEST = 'SEND ACTION_REQUEST';
export const SEND_ACTION_RECEIVE = 'SEND_ACTION_RECEIVE';
export const SEND_ACTION_ERROR = 'SEND_ACTION_ERROR';

export const SEND_INTRODUCED_ACTION = 'SEND_INTRODUCED_ACTION';
export const CHECK_VALIDATE_FORMS = 'CHECK_VALIDATE_FORMS';

export const VALIDATE_FORMS_ERROR = 'VALIDATE_FORMS_ERROR';
export const VALIDATE_FORMS_SUCCESS = 'VALIDATE_FORMS_SUCCESS';

export const FORMAT_MESSAGE = 'FORMAT_MESSAGE';
export const FORMAT_MESSAGE_SUCCESS = 'FORMAT_MESSAGE_SUCCESS';

export const HANDLER_DROPDOWN_COPY = 'HANDLER_DROPDOWN_COPY';
export const HANDLER_DROPDOWN_RUN = 'HANDLER_DROPDOWN_RUN';
export const HANDLER_DROPDOWN_DELETE = 'HANDLER_DROPDOWN_DELETE';

export const HANDLER_DELETE_ACTIONS = 'HANDLER_DELETE_ACTIONS';